package com.example.demo.service;

import com.example.demo.dao.PackageDAO;
import com.example.demo.dto.CreatePackageRequestDto;
import com.example.demo.dto.PackageDetailDto;
import com.example.demo.dto.PackageStatus;
import com.example.demo.model.ItineraryItem;
import com.example.demo.model.TourPackage;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class PackageService {
    public PackageService(PackageDAO packageDAO) {
        this.packageDAO = packageDAO;
    }

    private PackageDAO packageDAO;

    public List<TourPackage> findAllPackages() {
        return packageDAO.findAllPackages();
    }

    public  List<TourPackage> findPackagesByStatus(PackageStatus status){
        return packageDAO.findAllPackagesByStatus(status);
    }

    public PackageDetailDto findPackageBySlug(String slug){
        TourPackage thePackage = packageDAO.findPackageBySlug(slug);
        List<ItineraryItem> theItems = packageDAO.findAllItineraryItemsByPackageId(thePackage.getPackageId());
        return PackageDetailDto.from(thePackage,theItems);
    }

    public TourPackage createPackage(CreatePackageRequestDto requestDto) {
        // 1. Convert the DTO into a TourPackage model object.
        TourPackage newPackage = new TourPackage();
        newPackage.setName(requestDto.getName());
        newPackage.setTour_type(requestDto.getTour_type());
        newPackage.setImage_url(requestDto.getImage_url());
        newPackage.setDuration_days(requestDto.getDuration_days());
        newPackage.setPrice(requestDto.getPrice());
        newPackage.setMax_capacity(requestDto.getMax_capacity());
        newPackage.setItinerary_summary(requestDto.getItinerary_summary());
        newPackage.setStatus(requestDto.getStatus());
        // Note: slug and created_at are handled by the database. avg_rating is null by default.

        // 2. Call the DAO to save the new package and get its generated ID.
        Integer newPackageId = packageDAO.createPackage(newPackage);

        if (newPackageId == null) {
            throw new RuntimeException("Failed to create the package. No ID was returned.");
        }

        // 3. Fetch and return the newly created package by its ID.
        // This ensures we get the slug and created_at timestamp generated by the database.
        return packageDAO.findPackageById(newPackageId);
    }

    public ItineraryItem createItineraryItem(ItineraryItem theItem){
        System.out.println(theItem);
        Integer newItemId = packageDAO.createItineraryItem(theItem);
        System.out.println(newItemId);

        if(newItemId == null){
            throw new RuntimeException("Failed to create the itinerary item. No ID was returned.");
        }

        return packageDAO.findItineraryItemsById(newItemId);
    }
}
