package com.example.demo.service;

import com.example.demo.dao.PackageDAO;
import com.example.demo.dto.*;
import com.example.demo.model.ItineraryItem;
import com.example.demo.model.TourPackage;
import com.example.demo.util.AuthorizationService;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class PackageService {
    private final PackageDAO packageDAO;
    private final AuthorizationService authorizationService;

    public PackageService(PackageDAO packageDAO, AuthorizationService authorizationService) {
        this.packageDAO = packageDAO;
        this.authorizationService = authorizationService;
    }

    public List<TourPackage> findAllPackages() {
        return packageDAO.findAllPackages();
    }

    public  List<TourPackage> findPackagesByStatus(PackageStatus status){
        return packageDAO.findAllPackagesByStatus(status);
    }

    public PackageDetailDto findPackageBySlug(String slug){
        TourPackage thePackage = packageDAO.findPackageBySlug(slug);
        List<ItineraryItem> theItems = packageDAO.findAllItineraryItemsByPackageId(thePackage.getPackageId());
        return PackageDetailDto.from(thePackage,theItems);
    }

    public TourPackage createPackage(String authHeader, CreatePackageRequestDto requestDto) throws SecurityException {
        authorizationService.verifyPackageManagerStaff(authHeader);
        // 1. Convert the DTO into a TourPackage model object.
        TourPackage newPackage = new TourPackage();
        newPackage.setName(requestDto.getName());
        newPackage.setTour_type(requestDto.getTour_type());
        newPackage.setImage_url(requestDto.getImage_url());
        newPackage.setDuration_days(requestDto.getDuration_days());
        newPackage.setPrice(requestDto.getPrice());
        newPackage.setMax_capacity(requestDto.getMax_capacity());
        newPackage.setItinerary_summary(requestDto.getItinerary_summary());
        newPackage.setStatus(requestDto.getStatus());
        // Note: slug and created_at are handled by the database. avg_rating is null by default.

        // 2. Call the DAO to save the new package and get its generated ID.
        Integer newPackageId = packageDAO.createPackage(newPackage);

        if (newPackageId == null) {
            throw new RuntimeException("Failed to create the package. No ID was returned.");
        }

        // 3. Fetch and return the newly created package by its ID.
        // This ensures we get the slug and created_at timestamp generated by the database.
        return packageDAO.findPackageById(newPackageId);
    }

    public TourPackage updatePackage(String slug, UpdatePackageRequestDto requestDto, String authHeader) throws Exception {
        // Step 1: Authorize the user first. This is a secure gateway.
        authorizationService.verifyPackageManagerStaff(authHeader);

        // Step 2: Find the existing package by its slug.
        TourPackage existingPackage = packageDAO.findPackageBySlug(slug);

        // Step 3: If it doesn't exist, throw a specific exception for the controller to handle.
        if (existingPackage == null) {
            throw new Exception("Package with slug '" + slug + "' not found.");
        }

        // Step 4: Manually update the fields from the DTO.
        // This is the key step that prevents the Mass Assignment security vulnerability.
        existingPackage.setName(requestDto.getName());
        existingPackage.setTour_type(requestDto.getTour_type());
        existingPackage.setImage_url(requestDto.getImage_url());
        existingPackage.setDuration_days(requestDto.getDuration_days());
        existingPackage.setPrice(requestDto.getPrice());
        existingPackage.setMax_capacity(requestDto.getMax_capacity());
        existingPackage.setItinerary_summary(requestDto.getItinerary_summary());
        existingPackage.setStatus(requestDto.getStatus());

        // Step 5: Call the DAO to persist the changes.
        packageDAO.updatePackage(existingPackage);

        // Step 6: Return the fully updated package. This ensures we get the new slug if the name changed.
        return packageDAO.findPackageById(existingPackage.getPackageId());
    }

    public Integer deletePackage(String packageSlug, String authHeader) throws Exception{
        authorizationService.verifyPackageManagerStaff(authHeader);
        return packageDAO.deletePackage(packageSlug);
    }


    public ItineraryItem createItineraryItem(String authHeader, ItineraryItem theItem) throws SecurityException{
        authorizationService.verifyPackageManagerStaff(authHeader);
        Integer newItemId = packageDAO.createItineraryItem(theItem);

        if(newItemId == null){
            throw new RuntimeException("Failed to create the itinerary item. No ID was returned.");
        }

        return packageDAO.findItineraryItemsById(newItemId,theItem.getPackage_id());
    }

    public ItineraryItem updateItineraryItem(String packageSlug, Integer itemId, UpdateItineraryItemRequestDto updatedItem, String authHeader) throws Exception{
        authorizationService.verifyPackageManagerStaff(authHeader);
        // Step 2: Find the parent package first.
        TourPackage parentPackage = packageDAO.findPackageBySlug(packageSlug);
        if (parentPackage == null) {
            throw new Exception("Package with slug '" + packageSlug + "' not found.");
        }

        // Step 3: Find the itinerary item, ensuring it belongs to the correct package.
        ItineraryItem existingItem = packageDAO.findItineraryItemsById(itemId, parentPackage.getPackageId());
        if (existingItem == null) {
            throw new Exception("Itinerary item with ID '" + itemId + "' not found in package '" + packageSlug + "'.");
        }
        existingItem.setDay_number(updatedItem.getDay_number());
        existingItem.setDuration(updatedItem.getDuration());
        existingItem.setStart_time(updatedItem.getStart_time());
        existingItem.setEnd_time(updatedItem.getEnd_time());
        existingItem.setTitle(updatedItem.getTitle());
        existingItem.setDescription(updatedItem.getDescription());
        existingItem.setStreet_name(updatedItem.getStreet_name());
        existingItem.setCity(updatedItem.getCity());
        existingItem.setState(updatedItem.getState());
        existingItem.setPin(updatedItem.getPin());

        packageDAO.updateItineraryItem(existingItem);
        return packageDAO.findItineraryItemsById(itemId,existingItem.getPackage_id());
    }

    public Integer deleteItineraryItem(String packageSlug,Integer itemId, String authHeader) throws Exception{
        authorizationService.verifyAdminStaff(authHeader);
        TourPackage thePackage = packageDAO.findPackageBySlug(packageSlug);
        return packageDAO.deleteItineraryItem(itemId, thePackage.getPackageId());
    }
}
